### ISSUE TITLE
Readme examples don't work because latest version not published

### ISSUE THREAD

**Issue by amilajack** [alesgenova/colormap#23]
Again, thanks for the awesome project! Just wanted to bring this to your attention. [This was the commit](https://github.com/alesgenova/colormap/commit/4083625a9377d2d0154babc3aa7a94397b40f686) that broke the examples. Can be fixed by publishing the latest version of the package

**Comment by alesgenova** [comment]
Good catch, I cut a release and published it to npm!

I'm glad you're liking the project :)
